#!/bin/bash

docker_Version=$(docker -v)
var1="Docker version 1[7-9]*"
if [[ $docker_Version = $var1 ]]; then
   echo "Docker version ok"
else 
   echo "Docker version is too old"
fi


docker_Version=$(docker-compose -v)
var1="Docker version 1[.20-.25]*"
if [[ $docker_Version = $var1 ]]; then
   echo "Docker version ok"

else
     echo "Docker-compose need update"
	 
	 sudo curl -L "https://github.com/docker/compose/releases/download/1.25.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
     sudo chmod +x /usr/local/bin/docker-compose
	 
fi
