apiVersion : apps/v1
kind: Deployment
metadata:
  name: fasterimage 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fasterimage
  template:
    metadata:
      labels:
        app: fasterimage 
    spec:
      containers:
        - name: fasterimage 
          image: aakmiha.azurecr.io/fasterimage:latest
          ports:
          - containerPort: 80
