apiVersion : apps/v1
kind: Deployment
metadata:
  name: imagefast
spec:
  replicas: 1
  selector:
    matchLabels:
      app: imagefast
  template:
    metadata:
      labels:
        app: imagefast
    spec:
      containers:
        - name: imagefast
          image: arcmiha.azurecr.io/imagefast:228
          ports:
          - containerPort: 80

