apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: fasterimage 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: fasterimage 
    spec:
      containers:
        - name: fasterimage 
          image: aakmiha.azurecr.io/fasterimage
          ports:
          - containerPort: 80