apiVersion : apps/v1
kind: Deployment
metadata:
  name: fast
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fast
  template:
    metadata:
      labels:
        app: fast
    spec:
      containers:
        - name: fast
          image: aakmiha.azurecr.io./fast
          ports:
          - containerPort: 80

