apiVersion : apps/v1
kind: Deployment
metadata:
  name: fastermikemaster 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastermikemaster
  template:
    metadata:
      labels:
        app: fastermikemaster 
    spec:
      containers:
        - name: fastermikemaster 
          image: fastermikemaster
          ports:
          - containerPort: 80
